/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eloading;

/**
 *
 * @author johna
 */
public class anoLoadmo extends javax.swing.JFrame {

    /**
     * Creates new form anoLoadmo
     */
    public anoLoadmo() {
        initComponents();
    }
    int load;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        regular20 = new javax.swing.JLabel();
        unliCall10 = new javax.swing.JLabel();
        psstPogi150 = new javax.swing.JLabel();
        goJabol69 = new javax.swing.JLabel();
        unliText10 = new javax.swing.JLabel();
        goSurf50 = new javax.swing.JLabel();
        buy = new javax.swing.JButton();
        gs50 = new javax.swing.JCheckBox();
        gj69 = new javax.swing.JCheckBox();
        ut10 = new javax.swing.JCheckBox();
        gp150 = new javax.swing.JCheckBox();
        r20 = new javax.swing.JCheckBox();
        uc10 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regular20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eloading/r20s.png"))); // NOI18N
        getContentPane().add(regular20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 60, 50));

        unliCall10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unliCall10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eloading/uc10s.png"))); // NOI18N
        getContentPane().add(unliCall10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 50));

        psstPogi150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eloading/pp150s.png"))); // NOI18N
        getContentPane().add(psstPogi150, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 60, 50));

        goJabol69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eloading/gj69s.png"))); // NOI18N
        getContentPane().add(goJabol69, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 70, 50));

        unliText10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eloading/ul10s.png"))); // NOI18N
        getContentPane().add(unliText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 50));

        goSurf50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eloading/gs50s.png"))); // NOI18N
        getContentPane().add(goSurf50, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, 50));

        buy.setText("BUY");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });
        getContentPane().add(buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        buttonGroup.add(gs50);
        gs50.setText("GOSURF 50");
        gs50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gs50ActionPerformed(evt);
            }
        });
        getContentPane().add(gs50, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        buttonGroup.add(gj69);
        gj69.setText("GOJABOL 69");
        getContentPane().add(gj69, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        buttonGroup.add(ut10);
        ut10.setText("UNLI TEXT 10");
        getContentPane().add(ut10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        buttonGroup.add(gp150);
        gp150.setText("UNLI PSST 150");
        getContentPane().add(gp150, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        buttonGroup.add(r20);
        r20.setText("REGULAR 20");
        getContentPane().add(r20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        buttonGroup.add(uc10);
        uc10.setText("UNLI CALL 10");
        getContentPane().add(uc10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
        if(uc10.isSelected()) load = 10;
        else if(gs50.isSelected()) load = 50;
        else if(gj69.isSelected()) load = 69;
        else if(ut10.isSelected()) load = 10;
        else if(gp150.isSelected()) load = 150;
        else if(r20.isSelected()) load = 20;
        
        
        magkanoPo opo = new magkanoPo();
        
        opo.totalLoad = load;
        
        opo.show();
        dispose();
        
    }//GEN-LAST:event_buyActionPerformed

    private void gs50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gs50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gs50ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
            atePaloadpo sigena = new atePaloadpo();
            sigena.show();
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anoLoadmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anoLoadmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anoLoadmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anoLoadmo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new anoLoadmo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buy;
    private javax.swing.JCheckBox gj69;
    private javax.swing.JLabel goJabol69;
    private javax.swing.JLabel goSurf50;
    private javax.swing.JCheckBox gp150;
    private javax.swing.JCheckBox gs50;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel psstPogi150;
    private javax.swing.JCheckBox r20;
    private javax.swing.JLabel regular20;
    private javax.swing.JCheckBox uc10;
    private javax.swing.JLabel unliCall10;
    private javax.swing.JLabel unliText10;
    private javax.swing.JCheckBox ut10;
    // End of variables declaration//GEN-END:variables
}
