/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eloading;
import java.io.*;
import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author johna
 */
public class atePaloadpo extends javax.swing.JFrame {

    /**
     * Creates new form atePaloadpo
     */
    public atePaloadpo() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suff2TF = new javax.swing.JTextField();
        suff1TF = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suff2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suff2TFActionPerformed(evt);
            }
        });
        getContentPane().add(suff2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 92, 160, 40));

        suff1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suff1TFActionPerformed(evt);
            }
        });
        getContentPane().add(suff1TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, 40));

        btn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btn.setText("CONTINUE");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eloading/STUDENT DATABASE (1).gif"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        DecimalFormat df = new DecimalFormat("0.00");
        Scanner sc = new Scanner(System.in);

        int len,tl,unli;
        String suff1,suff2;
        double load=500.00,al,total;


        try{
        System.out.println("----------LOADING STATION EMMULATOR----------");
        System.out.println("Available Load:"+df.format(load));
        System.out.print("Enter 4-digits suffix: ");
        suff1= suff1TF.getText();
        
                if(suff1.equals("0918")||suff1.equals("0919")||suff1.equals("0916")||suff1.equals("0917")||suff1.equals("0922")||suff1.equals("0923")||suff1.equals("0933"))

                {
                System.out.print("Enter 7-digits suffix: ");
                suff2=suff2TF.getText();
                len=suff2.length();

                        if(len==7)
                        {
                            anoLoadmo begin = new anoLoadmo();
                            begin.show();
                            dispose();
                            
                        }
                }

        }catch(Exception a){
        System.out.println("Enter Number Only");
        JOptionPane.showMessageDialog(null, "Enter numbers only");
}
    }//GEN-LAST:event_btnActionPerformed

    private void suff2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suff2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suff2TFActionPerformed

    private void suff1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suff1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suff1TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atePaloadpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atePaloadpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atePaloadpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atePaloadpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atePaloadpo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn;
    private javax.swing.JTextField suff1TF;
    private javax.swing.JTextField suff2TF;
    // End of variables declaration//GEN-END:variables
}
